### ISSUE TITLE
Feature Request: Code Highlighting

### ISSUE THREAD

**Issue by olpo24** [misterunknown/ifm#109]
Hi,

Thanks for this great tool.
Can you add code higlighting für the file editor?

Best regards
Ole

**Comment by misterunknown** [comment]
Hi,

I don't want to add syntax highlighting by default, because I want to keep the IFM as light as possible; it should not exceed 1MB.

However, you can create a custom build with ace features, which is explained [in the wiki](https://github.com/misterunknown/ifm/wiki/Syntax-highlighting-and-other-Ace-features).

Let me know if you have any trouble doing so.

Cheers,
Marco

**Comment by olpo24** [comment]
Hallo Marco,

 

ich hab ja echt keine Ahnaung von dem ganzen git clone zeugs etc., aber ich habe es hinbekommen!

 

Vielen Dank!

 

Beste Grüße

 

Ole

 

Gesendet: Freitag, 07. Juni 2019 um 09:38 Uhr
Von: "Marco Dickert" <notifications@github.com>
An: misterunknown/ifm <ifm@noreply.github.com>
Cc: olpo24 <o.poetter@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [misterunknown/ifm] Feature Request: Code Highlighting (#109)


Hi,

I don't want to add syntax highlighting by default, because I want to keep the IFM as light as possible; it should not exceed 1MB.

However, you can create a custom build with ace features, which is explained in the wiki.

Let me know if you have any trouble doing so.

Cheers,
Marco
