### ISSUE TITLE
Instances with dynamic Configurations

### ISSUE THREAD

**Issue by andrewteg** [misterunknown/ifm#110]
I loaded two instances to get 2 different root directories with code like:

>
    require_once( "/any/where/libifm.php" );
    $YOUR_CUSTOM_CONFIG = array('root_dir' => $file_root); // get the config array from anywhere
    $ifm = new IFM( $YOUR_CUSTOM_CONFIG );
    $ifm->run();`

It works well if I hard code the $file_root variable as:
    `$file_root = '/folder/1';`

However, I tried to set it up with a querystring variable so that url.php?id=1 and url.php?id=2 start in different folders, and that always just loads the same root folder.  I added error_log and it appears the code run multiple times and does not keep the _GET variable. Is there another way to go about dynamic starting points?
>
    include_once('/app/config.php');
    //setup path
    $file_root = ROOT_PATH.'/files/projects/1/'; //works at url1.php
    $file_root = ROOT_PATH.'/files/projects/2/'; //works at url2.php
    $file_root = ROOT_PATH.'/files/projects/'.$_GET['id'].'/'; //fails at url.php?id=1 or 2
    if (!is_dir($file_root)) mkdir($file_root, 0777, true);
    error_log('file_root='.$file_root);
    //setup ifm
    require_once(ROOT_PATH.'/files/ifm-master/build/libifm.php');
    $ifm = new IFM(array('root_dir' => $file_root));
    $ifm->run();

Thanks for any suggestions,
Andrew

**Comment by misterunknown** [comment]
Hi Andrew,

the problem is that the javascript part of the IFM uses `window.location.pathname` as its API endpoint ([ifm.js, line 12](https://github.com/misterunknown/ifm/blob/master/src/ifm.js#L12)), which does not include GET parameters. I guess it should be possible to use `window.location.href` instead, but I'd like to do some tests before I push that.

For now you could simply change the mentioned line to
```
self.api = params.api || window.location.href;
```
and it should work.

Cheers,
Marco
