### ISSUE TITLE
Resize Editor 

### ISSUE THREAD

**Issue by olpo24** [misterunknown/ifm#119]
Hi,

is there a way to resize the editor window?

Best regards,
Ole

**Comment by misterunknown** [comment]
Hi,

I just pushed an update, where you can toggle the ace editor full screen with <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f</kbd>.

Would that be sufficient for you? It should be possible to make the ace editor resizable by the user, but I'm not an experienced javascript developer, so that would take me some time.

Cheers, \
Marco

**Comment by olpo24** [comment]
Hi Marco,
thanks for your quick reply.
Just a stupi question. I integrated syntax highlighting as descriped here [https://github.com/misterunknown/ifm/wiki/Syntax-highlighting-and-other-Ace-features](url).

So now with your update I have to do the steps again, rigt?

Best regards,
Ole

**Comment by misterunknown** [comment]
> So now with your update I have to do the steps again, rigt?

Well, yes, but not completely. If you still have the repository available, with the additional ace files under `src/includes/ace/`, you can just pull my changes, and recompile the IFM. The `src/includes/ace` directory is listed in the `.gitignore`, so they will not be removed:

```
git pull
./compiler.php --languages=en
```
(adjust language if necessary)
