### ISSUE TITLE
Request password protect

### ISSUE THREAD

**Issue by nhymxu** [misterunknown/ifm#3]
Password protect file?

**Comment by dottornova** [comment]
I'ts very usefull and beautifull, but if is possible it would be better if script had a login area with username and password befur run

**Comment by misterunknown** [comment]
I will note that on my todo list. It should be not that hard to implement a session based authentification which works independent from the webserver.

**Comment by misterunknown** [comment]
I added a super simple authentication method using sessions. It is a really basic feature since you can only configure only **one single user**.

Multiple users may be desirable, but thus you cannot assign permissions at the moment, I delay this feature a bit ;) It will be enormous work to add a real user management and that is also not really the use case for this script.

**Comment by dottornova** [comment]
the individual user is sufficient to prevent unwanted access via url, for have security!
Thanks so much

**Comment by misterunknown** [comment]
Nice. Tell me if you notice any errors.

**Comment by dottornova** [comment]
after change auth from 0 to 1
Fatal error: Call to undefined function password_verify() in  ....   on line 1537

**Comment by misterunknown** [comment]
Ok... Seems that you use a PHP version below 5.5 where the password_verify function does not exist. You may either upgrade to PHP5.5 (or newer) or use an extra library, like [this one](https://github.com/Antnee/phpPasswordHashingLib), providing the PHP 5.5 password functions.

That said, I certainly have to edit the requirements for this script.

**Comment by dottornova** [comment]
thank's so muche for your link i'll try to extra library on ifm.php
this script is very beautiful!

If i can suggest, another interesting function for ifm can be full path navigation, for example if i put ifm on a sub/sub/ folder, the ability to navigate up, and go up and up on server folder

**Comment by misterunknown** [comment]
> thank's so much for your link, i'll try to add extra library on ifm.php
> this script is very beautiful!

Thank you :)

> If i can suggest, another interesting function for ifm can be full path navigation, for example if i put ifm on a sub/sub/ folder, the ability to navigate up, and go up and up on server folder

Well, this request touches another security consideration, because per default PHP is allowed to operate on the whole filesystem tree as long as the user (mostly www-data) has the relevant permissions, but maybe I'll implement a configuration option for limiting the "range of operation" to either the scripts location or the document root of the webserver.

However you should create a new issue for that topic, because it's like a new feature request ;) Thanks!

ps: Please let me know if the mentioned library works ;)

**Comment by dottornova** [comment]
thanks tomorrow i modify script and make test

**Comment by misterunknown** [comment]
Guess this can be closed.
