### ISSUE TITLE
Multi file upload

### ISSUE THREAD

**Issue by jrondorf** [misterunknown/ifm#50]
Possibility to upload more than one file. 

Either use file input multiple (and do not support a direct file rename then), or use a library like dropzone.js

I am not thinking of uploading whole directories, but the possibility to either drag and drop selected files onto the file upload (or dropzone.js area), or being able to use multi selection in the browser file input selection dialog.

**Comment by misterunknown** [comment]
Thanks for the hint, I didn't know dropzone.js yet. Seems to be a nice library.

**Comment by misterunknown** [comment]
I didn't use dropzone.js eventually, because this wasn't really necessary. The version in branch [issue-50](https://github.com/misterunknown/ifm/tree/issue-50) now supports multiple files. I also had to redesign the task handling. I'm not completely happy with the design, but it works for now. 

Of course, I will design the input field for the files, so that it looks like a drop area. But dropping files should work already in modern browsers.

**Comment by jrondorf** [comment]
Just tested, works great already. Good job, thanks!

**Comment by jrondorf** [comment]
Will check if I make a dropzone.js implementation based on your work in branch issue-50 in my fork, where users are able to drag and drop files on the table ;-)

**Comment by misterunknown** [comment]
I just did that^^ Check out the newest commit in branch issue-50.

**Comment by jrondorf** [comment]
That works perfectly. Thanks!

**Comment by misterunknown** [comment]
Thanks for testing it so fast :smile:
