### ISSUE TITLE
New icons for options

### ISSUE THREAD

**Issue by jrondorf** [misterunknown/ifm#56]
I would like to add multi language support in my fork and create a pull request.

I guess the mustache.js lib will help in creating multi language support.

In order to be able to perform the language change, it would be great to have following icons (or sort of) available in the custom icon set (not only for language change, but also for editor options):

http://fontawesome.io/icon/cog/
http://fontawesome.io/icon/sliders/
http://fontawesome.io/icon/wrench/
http://fontawesome.io/icon/globe/
http://fontawesome.io/icon/language/

**Comment by misterunknown** [comment]
Most of them are already available, except `globe` and `language`. I'll add them in a minute.

**Comment by jrondorf** [comment]
Thanks. Would you welcome multi language support?

I would try to solve this with language files (one file per language), pulled into the main file like you did with the templates, and rendering with mustache variables. Any better idea?

**Comment by misterunknown** [comment]
Yes, of course, language support would be really nice. Your approach is good, I don't have any better idea. I'm think some simple json files are sufficient for that.

The problem is, that I want to keep the script as leightweight as possible, since some webhosters limit the size of PHP scripts, so the compiler should only supply one language per build, as long as the user doesn't want to have a multi-language script. I don't really know how to handle that. I thought of separating the builds from the code by creating a new repository "ifm-builds", where anyone can download his precompiled version. Furthermore, I would add a compiler option which specifies which language(s) should be included, in case the user wants to compile the IFM himself. This would also solve the problem of committing: At the moment it is unclear if a pull request should contain the newly build ifm.php or just the changed files from the `src` directory. What do you think?

**Comment by jrondorf** [comment]
IMHO, in the case you want to keep the size as small as possible I wouldn't load all possible languages into the main php file, but only the language, which is configured in compile.php.
(If you are concerned about file size, best would be to separate all assets into a separate folder, but that is another story.)

I would then add a German text file into addition of it, and we can discuss then where this and other languages should be stored. Adding languages should only contain one new languages source file.

Will start tomorrow on that 😉

**Comment by misterunknown** [comment]
Sounds nice! For the languages I would suggest to create `src/languages`. Thanks again for your participation!
