### ISSUE TITLE
Feature Request (multi-user)

### ISSUE THREAD

**Issue by ascargataa** [misterunknown/ifm#89]
Is possible set differet root_dir for different users?
(different configurations would be perfect)

TNX

**Comment by misterunknown** [comment]
Well, at the moment this is not possible. This whole authentication mechanism was more or less a quick hack for people which weren't able to set up a basic authentication with the webserver. Furthermore I want to keep the IFM as leightweight as possible, so the login is designed only for authentication, not authorization.

Nevertheless, I [see the need for a more sophisticated user _and_ permission management](https://github.com/misterunknown/ifm/issues/32), so I [started to write a wrapper](https://github.com/misterunknown/ifm-manager) around the IFM which suffices this needs. Unfortunately this is not really working at the moment, but it's definitely on my todo list ;)

**Comment by ascargataa** [comment]
ok thanks .. I really like the application, with this feature it would be perfect for me

**Comment by misterunknown** [comment]
By the way, if you use the apache2 webserver and the basic authentication, you could work around by setting environment variables via the VHost configuration or .htaccess (until the function is implemented):
```
RequestHeader set X-Remote-User expr=%{REMOTE_USER}

SetEnvIf X-Remote-User "ascargataa" IFM_ROOT_DIR=/path/to/dir
SetEnvIf X-Remote-User "other_user" IFM_ROOT_DIR=/path/to/other_dir
...
```
But please note: if you set these in a .htaccess file, remember to disable the "showhtdocs" option, because otherwise a user can edit this file and set his own permissions.

**Comment by ascargataa** [comment]
ok, I'll try

Tnx

**Comment by misterunknown** [comment]
As I'm not able to put much effort in this, I'll close this issue. Sorry.
