### ISSUE TITLE
Doesn't Run. Error!

### ISSUE THREAD

**Issue by exonas** [misterunknown/ifm#93]
I am getting this error:

PHP Parse error:  syntax error, unexpected '{' in ifm.php on line 3834

Any idea?

**Comment by misterunknown** [comment]
Weird. Which PHP version do you use? Can you paste the lines 3830-3840 here?

**Comment by exonas** [comment]
I am using PHP 5.6 (CentOS 7). I also tried with PHP 7.1 but didn't work. Is it an extension issue?

Here are the 10 lines

	}
					$this->fileDownload( array( "file" => $dfile, "name" => $d['filename'] . ".zip" ) );
				} catch ( Exception $e ) {
					echo $this->l['error'] . " " . $e->getMessage();
				} finally {
					if( file_exists( $dfile ) ) @unlink( $dfile );
				}
			}
		}
	}

**Comment by misterunknown** [comment]
Well, this is indeed weird. I just installed a CentOS container and get the same error. It shouldn't be an extension issue, as there are no extensions used in the referred lines...

At least I can reproduce this error, so I'll investigate a bit, and let you know what I found out.

**Comment by misterunknown** [comment]
The problem is, that CentOS 7 comes with PHP 5.4 which does not support the `finally` statment in try-catch blocks. You have to use at least PHP 5.6 for the IFM to work.

To validate this, I installed PHP 7.0 in my CentOS 7 container, and the IFM instantly worked. Are you sure that you tested this with PHP 7? What do you get if you invoke a script containing the following content:
```
<?php

echo PHP_VERSION;
```

**Comment by exonas** [comment]
I am sorry it was my mistake. I installed the wrong version of PHP. Thanks a lot for quick response

**Comment by misterunknown** [comment]
No problem ;)
